ordering:
  home: ''
  registration: ''
  login:
    __module-uC7Wk: ''
  logout: ''
  member: ''
  mycart:
    __module-MfJJJ: ''
items:
  home:
    id: 103
    hash: ''
    dropdown_hide: ''
    width: auto
    class: ''
    icon: 'fa fa-home'
  registration:
    id: 154
    hash: ''
    dropdown_hide: '0'
    width: auto
    class: ''
    icon: 'fa fa-user-plus'
  login:
    id: 158
    hash: ''
    dropdown_hide: '0'
    width: auto
    class: ''
    icon: 'fa fa-sign-in'
  logout:
    id: 162
    hash: ''
    dropdown_hide: '0'
    width: auto
    class: ''
    icon: 'fa fa-sign-out'
  member:
    id: 160
    hash: ''
    dropdown_hide: '0'
    width: auto
    class: ''
    icon: 'fa fa-user'
  mycart:
    id: 159
    hash: ''
    dropdown_hide: '0'
    width: auto
    class: ''
    icon: 'fa fa-shopping-cart'
  login/__module-uC7Wk:
    type: particle
    particle: module
    title: 登入
    options:
      particle:
        enabled: '1'
        module_id: '118'
        chrome: ''
      block:
        extra: {  }
  mycart/__module-MfJJJ:
    type: particle
    particle: module
    title: 購物車模組
    options:
      particle:
        enabled: '1'
        module_id: '98'
        chrome: ''
      block:
        extra: {  }
