name: 9
timestamp: 1445241672
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1445234641
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
