name: 9
timestamp: 1446011950
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1445336231
positions:
  search: Search
  navigation: 'Module Position'
  breadcrumbs: Breadcrumbs
  module-instance: 'Module Position'
  footer: Footer
