preset:
  image: gantry-admin://images/layouts/default.png

layout:
  header:
    container:
      - [particle-logo 30, position-header 70]

  navigation:
    container:
      - particle-menu

  main:
    container:
      - position-breadcrumbs
      - system-messages
      - pagecontent

  footer:
    container:
    - position-footer
    - [particle-copyright 40, spacer 30, particle-branding 30]

  offcanvas:
    - particle-mobile-menu
