name: 10
timestamp: 1446453570
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1445426747
positions:
  search: Search
  navigation: 'Module Position'
  footer: Footer
